on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

name: daily-game

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      # Use GitHub's automatic token for pushing commits
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          restore-cache: true
          packages: |
            any::dplyr
            any::ggplot2
            any::ggforce

      - name: Run simulation script
        run: Rscript simulate_game.R

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git status
          git branch
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "plot updated"
            git fetch origin master
            git rebase origin/master
            git push origin HEAD:master
          fi
